# ==========================================================
# Yaba Bigo | Render Blueprint (Production) - CORRECTED
# ==========================================================

services:
  # 1. Django Backend (Web Service)
  - type: web # <-- Added hyphen and correct indentation
    name: yaba-bingo-backend
    env: python
    rootDir: ./backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "daphne yaba_bingo.asgi:application --port $PORT --bind 0.0.0.0"
    healthCheckPath: /api/health/
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: DJANGO_SECRET_KEY
        sync: false
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        sync: false

  # 2. React Frontend (CHANGED TO FREE STATIC SITE)
  - type: static_site # <--- THIS IS THE CHANGE THAT MAKES IT FREE
    name: yaba-bingo-frontend
    rootDir: ./frontend
    buildCommand: "npm install && npm run build"
    # startCommand is removed because it's not needed for a static_site
    # buildFilter is removed for simplicity, Render will build it on every push
    staticPublishPath: dist # This tells Render where the built files are
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: yaba-bingo-backend
          property: url # <--- CORRECTED: 'url' is required for public access